### ISSUE TITLE
Error about the workflow "Get latest release from template"

### ISSUE THREAD

**Issue by skq1998** [ObsidianPublisher/follow_template#1]
Firstly,when I used the template-gh-pages, everything works. After that i run the workflow "Get latest release from template", then I can't finish the workflow "Publish". I get this

```text
Run venv/bin/python3 -m mkdocs build
INFO    -  "highlightjs" feature is disabled in your plugin configuration.
INFO    -  "mermaid2" feature is disabled in your plugin configuration.
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: /home/runner/work/skq1998.github.io/skq1998.github.io/site
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/runner/work/skq1998.github.io/skq1998.github.io/venv/lib/python3.11/site-packages/mkdocs/__main__.py", line 361, in <module>
    cli()
  File "/home/runner/work/skq1998.github.io/skq1998.github.io/venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/skq1998.github.io/skq1998.github.io/venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/runner/work/skq1998.github.io/skq1998.github.io/venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/skq1998.github.io/skq1998.github.io/venv/lib/python3.11/site-packages/click/core.py", line [14](https://github.com/skq1998/skq1998.github.io/actions/runs/5776462085/job/15655623239#step:7:15)34, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/skq1998.github.io/skq1998.github.io/venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/skq1998.github.io/skq1998.github.io/venv/lib/python3.11/site-packages/mkdocs/__main__.py", line 286, in build_command
    build.build(cfg, dirty=not clean)
  File "/home/runner/work/skq1998.github.io/skq1998.github.io/venv/lib/python3.11/site-packages/mkdocs/commands/build.py", line 304, in build
    files = config.plugins.on_files(files, config=config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/skq1998.github.io/skq1998.github.io/venv/lib/python3.11/site-packages/mkdocs/plugins.py", line 533, in on_files
    return self.run_event('files', files, config=config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/skq1998.github.io/skq1998.github.io/venv/lib/python3.11/site-packages/mkdocs/plugins.py", line 507, in run_event
    result = method(item, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/skq1998.github.io/skq1998.github.io/overrides/hooks/on_files.py", line 20, in on_files
    list_existing_pages(config, files)
  File "/home/runner/work/skq1998.github.io/skq1998.github.io/overrides/hooks/on_files.py", line [15](https://github.com/skq1998/skq1998.github.io/actions/runs/5776462085/job/15655623239#step:7:16), in list_existing_pages
    json.dump(pages, f, default=lambda o: o.__dict__, indent=4)
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/json/__init__.py", line [17](https://github.com/skq1998/skq1998.github.io/actions/runs/5776462085/job/15655623239#step:7:18)9, in dump
    for chunk in iterable:
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/json/encoder.py", line 430, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/json/encoder.py", line 326, in _iterencode_list
    yield from chunks
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/json/encoder.py", line 440, in _iterencode
    yield from _iterencode(o, _current_indent_level)
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/json/encoder.py", line 432, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/json/encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/json/encoder.py", line 440, in _iterencode
    yield from _iterencode(o, _current_indent_level)
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/json/encoder.py", line 432, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/json/encoder.py", line 406, in _iterencode_dict
    yield from chunks
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/json/encoder.py", line 440, in _iterencode
    yield from _iterencode(o, _current_indent_level)
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/json/encoder.py", line 439, in _iterencode
    o = _default(o)
        ^^^^^^^^^^^
  File "/home/runner/work/skq[19](https://github.com/skq1998/skq1998.github.io/actions/runs/5776462085/job/15655623239#step:7:20)98.github.io/skq1998.github.io/overrides/hooks/on_files.py", line 15, in <lambda>
    json.dump(pages, f, default=lambda o: o.__dict__, indent=4)
                                          ^^^^^^^^^^
AttributeError: 'mappingproxy' object has no attribute '__dict__'. Did you mean: '__dir__'?
Error: Process completed with exit code 1.
```

I found that `update.yml` is used to download latest releas of `sync-template`.

```
jobs:
  get-env:
    runs-on: ubuntu-latest
    outputs:
      update: ${{ steps.version.outputs.update }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: get template version
        uses: robinraju/release-downloader@main
        with:
          latest: true
          repository: "ObsidianPublisher/sync_template"
          fileName: "update.txt"
      - name: compare version.txt and update.txt
        id: version
        run: |
          if [ ! -f version.txt ]; then
            mv update.txt version.txt
            echo "update=true" > $GITHUB_OUTPUT
          elif [[ "$(cat version.txt)" < "$(cat update.txt)" ]]; then
            echo "update=true" > $GITHUB_OUTPUT
            rm version.txt
            mv update.txt version.txt
          else
            echo "update=false" > $GITHUB_OUTPUT
            rm update.txt
          fi
```

And I check the code in `sync-template/v2.3.3`, I found the same thing with the error content

```py
import json
import posixpath
import os
from mkdocs.structure.files import Files
from mkdocs.config.defaults import MkDocsConfig
 
def list_existing_pages(config: MkDocsConfig, files: Files):
    pages = []
    output_dir = config['site_dir']
    for file in files:
        if file.is_documentation_page() or file.is_media_file():
            pages.append(file)
    
    with open(posixpath.join(output_dir, 'search', 'all_files.json'), 'w') as f:
        json.dump(pages, f, default=lambda o: o.__dict__, indent=4)
 
def on_files(files: Files, config: MkDocsConfig):
    if not (posixpath.exists(posixpath.join(config['site_dir'], 'search'))):
        os.makedirs(posixpath.join(config['site_dir'], 'search'))
    list_existing_pages(config, files)
    return files
```
Maybe you haven't released `sync-template/v2.3.4` sucessfully.

**Comment by Mara-Li** [comment]
Ah, thanks, I updated on my side the new version of existing page but forgot to publish the version

**Comment by Mara-Li** [comment]
Hello!
Update to 2.4.0 will fix this error! Thank you for your patience, I was too much sleepy to work on this little issue (ADHD intensifies xD).
